### ISSUE TITLE
Clicking a different symbols crashes sketch

### ISSUE THREAD

**Issue by larsenwork** [ahmedmigo/overrideit-sketchplugin#14]
1: Select a symbol
2: Open overrideit
3: Select a different symbol
4: Sketch crashes

**Comment by ahmedmigo** [comment]
I am aware of this issue it is because of the new update of sketch, I am digging deep in it and will solve it in the new update i hope soon

**Comment by Jasonchan91** [comment]
I'm facing the same issue as well. Sketch version 51. Which to get the fixes soon since this is really a good plugin 👍

**Comment by mikhailvoloshin** [comment]
Great idea for a plugin! would be super if you fix it out. I see the same issue with Sketch 51.2. If the plugin doesn't crash Sketch I would say this is a must-have plugin for all designers.
![image](https://user-images.githubusercontent.com/14905940/44521654-7625ba00-a6dc-11e8-8e56-733322305dc5.png)

**Comment by ahmedmigo** [comment]
the bug is fixed but it affected the selection.
you have to close the plugin and re open it when you change selection 
this is solution for now and I am still working on it to make it back working again

**Comment by mikhailvoloshin** [comment]
thanks for the workaround! and thanks for grooming it!

**Comment by ahmedmigo** [comment]
you are welcome, Hopefully it will be fixed soon :)

**Comment by Lustless** [comment]
Same as everyone above, but also it seems that the plugin isn't able to detect my overrides. I want to replace "Address" with "Street Address" and it doesn't say that there are any symbols with the text "Address"

**Comment by ahmedmigo** [comment]
@Lustless did you update to the last version?

**Comment by ahmedmigo** [comment]
Hello Finally the plugin is back with selection!
Please test it and tell me if it is working or not 
v0.2.2

**Comment by mikhailvoloshin** [comment]
Thanks mate! It seems like it works well for me.
