### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by jane00** [ahmedmigo/overrideit-sketchplugin#19]
when I select another symbol but they are the instances of the same master, the values in the overideit panel not changed. It shows the overrides values of the previous selected one ,not the current one.

**Comment by ahmedmigo** [comment]
good catch i will work on this

**Comment by ahmedmigo** [comment]
@jane00 the bug should be fixed now. can you check and tell me to close the board

**Comment by jane00** [comment]
yes. This bug is fixed. .. partically.  It still happens sometimes, but most of the times is OK.
