### ISSUE TITLE
isn't working

### ISSUE THREAD

**Issue by lostmonster** [ahmedmigo/overrideit-sketchplugin#23]
the plugin doesn't open a window when I press the shortcut or click the menu item with a symbol selected

**Comment by lostmonster** [comment]
it also doesn't offer text override box resizing

**Comment by brunoDegaspare** [comment]
Same issue here, it's not working and it won't open a window when clicking the Plugins menu or pressing the shortcut.

**Comment by ahmedmigo** [comment]
Hello @lostmonster @brunoDegaspare 
I figure out the issue and solve it in the new version of the plugin v0.3.11
feel free to test it and tell me if it works

**Comment by brunoDegaspare** [comment]
Hi @ahmedmigo 
Thanks for getting back to us. I've downloaded and installed the latest version, re-started Sketch and worked! Thank you soooo much! :)

**Comment by lostmonster** [comment]
0.3.11 fixed my issue. Thank you!
