### ISSUE TITLE
Long loading time for large library of symbols

### ISSUE THREAD

**Issue by GautierFavier** [ahmedmigo/overrideit-sketchplugin#3]
Hi,

Your plug in rocks!
I use it a lot when I have a large library of symbols, eg. Icons. It is particularly useful because I can search quickly for the icon I want by taping the name of it. 

However, I use Material icons and the library is pretty big. When I click on the drop-down to look for an icon, it takes ~5-6 second to load. It would be awesome to reduce the loading time.
![loadingtime](https://user-images.githubusercontent.com/4347641/40892019-dbc94ffe-67d3-11e8-9f0d-c60d5888804d.gif)

Keep up the good work!
Cheers.

**Comment by ahmedmigo** [comment]
@GautierFavier it is true and I am working now to improve the performance

**Comment by ahmedmigo** [comment]
@GautierFavier you can disable the unneeded libraries so the symbols will be less and it load faster! until i figure out a way to make it faster

**Comment by ahmedmigo** [comment]
now the performance is better, it take some time for rendering the images. 
but will work on it to make it faster! 
I will close the issue.
