### ISSUE TITLE
Suggestion - Attached the overrideit window to the right panel

### ISSUE THREAD

**Issue by GautierFavier** [ahmedmigo/overrideit-sketchplugin#5]
Hi,

More like a suggestion here.
It would be awesome to attach the overrideit window to the right panel so it easy to toggle. A bit like the Craft plugin. 
Don't know if it's possible.
![screen shot 2018-06-04 at 10 45 31 am](https://user-images.githubusercontent.com/4347641/40893506-f557d15a-67e4-11e8-837f-36c6bd616d13.png)

Cheers

**Comment by ahmedmigo** [comment]
hello @GautierFavier it is a very good idea but I am not sure for the applicability of it, but I will try to work to make it somehow inside sketch
