### ISSUE TITLE
Overrideit window doesn't respect multi-screen

### ISSUE THREAD

**Issue by davidsanders** [ahmedmigo/overrideit-sketchplugin#6]
Loving this plugin.

When I run the plugin it manifests on my Mac's screen, not on my second monitor where I'm working in sketch. I move it over to the second screen, where I'm working with Sketch and when I'm done I close the window. If I reopen the overrideit window, the position is not remembered, and it reopens on my Mac screen again. It's a small thing, just wanted to surface.

I would love if this could remember it's screen, position, and size.

Wonderful work!

**Comment by ahmedmigo** [comment]
@davidsanders thank you!
I am aware of this issue and working on fixing it

**Comment by ahmedmigo** [comment]
this issue is fixed in version 0.1.6
