### ISSUE TITLE
Interface is broken

### ISSUE THREAD

**Issue by tikshow** [ahmedmigo/overrideit-sketchplugin#7]
My interface is broken by default, tried to increase the size of the window but didn't help.

![kepernyofoto 2018-06-11 - 22 16 50](https://user-images.githubusercontent.com/4992490/41254980-6975dd4e-6dc5-11e8-9486-a03350f42f8e.png)

**Comment by ahmedmigo** [comment]
@tikshow which version of safari do you have ?

**Comment by tikshow** [comment]
@ahmedmigo 10.0.3.

**Comment by ahmedmigo** [comment]
well, this is the issue the plugin support safari version 10.1 or more.
Please update your safari.

**Comment by nafta-studio** [comment]
my windows don't appear .... ?

**Comment by ahmedmigo** [comment]
@nafta-studio can you tell me which version of sketch and OS you have?

**Comment by nafta-studio** [comment]
Sketch 50.2 and OS El Capitan 10.11.6
thx

**Comment by ahmedmigo** [comment]
@nafta-studio El Capitan in not supported, can you update to Sierra ?

**Comment by nafta-studio** [comment]
no i cant, my g5 do not support the new system ... what a shame
