### ISSUE TITLE
All dropdown say None 

### ISSUE THREAD

**Issue by ryanstockau** [ahmedmigo/overrideit-sketchplugin#8]
I've just installed the plugin via Runner and tried to use it after restarting Sketch. 

When I open the OverrideIt window, I click on a dropdown and they all say "None" instead of showing the list of available symbols, so I'm not able to use the plugin to override anything. If I use the normal Sketch override panel I can see them all fine, so they are all the correct sizes to override properly.

Is this an issue with the plugin or am I doing something wrong?

<img width="252" alt="screen shot 2018-06-20 at 15 03 26" src="https://user-images.githubusercontent.com/5791430/41638165-28afe75a-749b-11e8-9456-cbdab11e97b4.png">

**Comment by ryanstockau** [comment]
Update: I was able to fix this by downloading and using the previous version (0.1.6), so hopefully that helps you find a fix.

**Comment by ahmedmigo** [comment]
@ryanstockau which version of macOS do you have ?

**Comment by ryanstockau** [comment]
@ahmedmigo MacOS High Sierra, 10.13.1 (17B1003)

**Comment by ahmedmigo** [comment]
@ryanstockau can you test 0.1.8 and tell me if it is working or not?

**Comment by ryanstockau** [comment]
@ahmedmigo Works now, thank you!
